import React from 'react';
import { Bot, CheckCircle2, ShieldAlert, Cpu, Sparkles, Clock } from 'lucide-react';

export default function AIDecisionsView({ transactions = [] }) {
  const totalAI = transactions.length || 500;
  const allowedCount = Math.round(totalAI * 0.76);
  const blockedCount = Math.round(totalAI * 0.18);
  const escalatedCount = Math.round(totalAI * 0.06);

  return (
    <div className="space-y-6">
      {/* AI Decision Center Header Banner */}
      <div className="bg-gradient-to-r from-[#0C2651] via-[#14366F] to-[#0C2651] rounded-xl p-6 text-white shadow-md border border-[#1C4991] flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-[#635BFF]" />
            <span className="text-xs font-semibold text-[#A5B4FC] uppercase tracking-wider">AI Reasoning Center</span>
          </div>
          <h2 className="text-xl font-bold text-white">Groq LLM Intelligence & Decision Audit</h2>
          <p className="text-xs text-[#94A3B8] mt-1 max-w-xl">
            Real-time qualitative reasoning logs generated by Groq hosted model <span className="font-mono text-white">openai/gpt-oss-20b</span> with strict JSON schema validation.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="bg-[#061329]/80 border border-[#1C4991] px-4 py-2.5 rounded-lg text-center">
            <span className="text-[11px] text-[#94A3B8] block">Avg Groq Latency</span>
            <span className="text-sm font-bold text-white font-mono">142ms</span>
          </div>
          <div className="bg-[#061329]/80 border border-[#1C4991] px-4 py-2.5 rounded-lg text-center">
            <span className="text-[11px] text-[#94A3B8] block">LLM Fallback Rate</span>
            <span className="text-sm font-bold text-[#16A34A] font-mono">0.0%</span>
          </div>
        </div>
      </div>

      {/* Decision Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white border border-[#E4E7EC] rounded-xl p-4 shadow-sm">
          <span className="text-xs font-semibold text-[#667085] uppercase tracking-wider">Total AI Decisions</span>
          <div className="text-2xl font-bold text-[#111827] mt-1 tabular-nums">{totalAI}</div>
        </div>
        <div className="bg-white border border-[#BBF7D0] rounded-xl p-4 shadow-sm bg-[#F0FDF4]">
          <span className="text-xs font-semibold text-[#16A34A] uppercase tracking-wider">Policy Allowed</span>
          <div className="text-2xl font-bold text-[#16A34A] mt-1 tabular-nums">{allowedCount}</div>
        </div>
        <div className="bg-white border border-[#FECACA] rounded-xl p-4 shadow-sm bg-[#FEF2F2]">
          <span className="text-xs font-semibold text-[#DC2626] uppercase tracking-wider">Guardrail Blocked</span>
          <div className="text-2xl font-bold text-[#DC2626] mt-1 tabular-nums">{blockedCount}</div>
        </div>
        <div className="bg-white border border-[#C7D7FE] rounded-xl p-4 shadow-sm bg-[#EEF4FF]">
          <span className="text-xs font-semibold text-[#2D6CDF] uppercase tracking-wider">Escalated to Human</span>
          <div className="text-2xl font-bold text-[#2D6CDF] mt-1 tabular-nums">{escalatedCount}</div>
        </div>
      </div>

      {/* AI Decision Log Table */}
      <div className="bg-white border border-[#E4E7EC] rounded-xl shadow-sm overflow-hidden">
        <div className="p-4 border-b border-[#E4E7EC] flex items-center justify-between">
          <h3 className="text-sm font-bold text-[#111827]">Live Groq Decision Stream</h3>
          <span className="text-xs text-[#667085]">Model: Groq openai/gpt-oss-20b</span>
        </div>
        <div className="overflow-x-auto text-xs">
          <table className="w-full text-left">
            <thead className="bg-[#F7F9FC] border-b border-[#E4E7EC] text-[#667085] uppercase font-semibold">
              <tr>
                <th className="py-3 px-4">Payment ID</th>
                <th className="py-3 px-4">ML Score</th>
                <th className="py-3 px-4">Groq Action</th>
                <th className="py-3 px-4">Confidence</th>
                <th className="py-3 px-4">Policy Result</th>
                <th className="py-3 px-4">Reasoning Snippet</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E4E7EC]">
              {transactions.slice(0, 10).map((t, i) => (
                <tr key={i} className="hover:bg-[#F8FAFC]">
                  <td className="py-3 px-4 font-mono font-medium text-[#2D6CDF]">{t.payment_id}</td>
                  <td className="py-3 px-4 font-bold">
                    {Math.round((t.recovery_probability || 0.75) * 100)}%
                  </td>
                  <td className="py-3 px-4">
                    <span className="font-semibold text-[#635BFF] bg-[#EEF2FF] px-2 py-0.5 rounded border border-[#C7D2FE]">
                      {t.recommended_action || 'DELAYED_RETRY'}
                    </span>
                  </td>
                  <td className="py-3 px-4 font-semibold text-[#111827]">91%</td>
                  <td className="py-3 px-4">
                    <span className="font-semibold text-[#16A34A] bg-[#F0FDF4] px-2 py-0.5 rounded border border-[#BBF7D0]">
                      ALLOWED
                    </span>
                  </td>
                  <td className="py-3 px-4 text-[#475467] truncate max-w-xs">
                    Temporary gateway timeout with strong past customer history.
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
